/**
 * English strings, keyed for later localisation. All visible text lives here
 * rather than in art or code paths (spec §05).
 */
export const en: Record<string, string> = {
  'game.title': 'Sisyphus: Unchained',

  'site.first_hill': 'The First Hill',
  'site.tartarus_rim': 'The Tartarus Rim',
  'site.leaking_heights': 'The Leaking Heights',
  'site.bronze_pass': 'The Bronze Pass',
  'site.skyward_escarpment': 'The Skyward Escarpment',
  'site.olympian_approach': 'The Olympian Approach',

  'work.hermes': 'Hermes Dispatch',
  'work.hermes.desc': 'Hermes stamps every delivery docket. All income ×1.25.',
  'work.daedalus': 'Daedalus Workshop',
  'work.daedalus.desc': 'An elegant geared linkage replaces the rough one. All income ×2.',
  'work.ixion': 'Ixion Drive',
  'work.ixion.desc': 'The eternal wheel finally turns something useful. All income ×2.',
  'work.danaids': 'Danaid Waterworks',
  'work.danaids.desc': 'The vessel never fills, but its leak drives a paddle wheel. All income ×2.',
  'work.talos': 'Talos Heavy Labor',
  'work.talos.desc': 'The bronze giant moves the great lever without effort. All income ×2.',
  'work.atlas': 'Atlas Support Contract',
  'work.atlas.desc': 'A frame takes the route’s load while Atlas still bears the sky. All income ×2.',
  'work.charter': 'Eternal Labor Charter',
  'work.charter.desc': 'Zeus contracts the enterprise for its own punishment. All income ×2.',

  'story.first_summit.god': 'The stone shall return to the foot of the hill.',
  'story.first_summit.sis': 'Convenient. I was going to need it again.',
  'story.flywheel_purchase.god': 'The return is part of your punishment.',
  'story.flywheel_purchase.sis': 'Then I shall make full use of it.',
  'story.foreman_contract.god': 'Your labor must continue without end.',
  'story.foreman_contract.sis': 'I have arranged shifts.',
  'story.tartarus_offer.god': 'Your assigned stone is insufficiently burdensome.',
  'story.tartarus_offer.sis': 'Is the larger one included?',
  'story.daedalus_purchase.god': 'No mortal may alter the terms.',
  'story.daedalus_purchase.sis': 'We altered the pulley.',
  'story.ixion_purchase.god': 'The wheel must turn eternally.',
  'story.ixion_purchase.sis': 'At last, a reliable supplier.',
  'story.leaking_offer.god': 'This vessel shall never be filled.',
  'story.leaking_offer.sis': 'That is the specification.',
  'story.bronze_offer.god': 'Mortal strength shall no longer suffice.',
  'story.bronze_offer.sis': 'I was hoping you would say that.',
  'story.talos_purchase.god': 'No unauthorized handling of divine substances.',
  'story.talos_purchase.sis': 'The ankle fitting is sealed.',
  'story.skyward_offer.god': 'The burden shall approach the weight of heaven.',
  'story.skyward_offer.sis': 'Atlas has submitted a quote.',
  'story.olympus_offer.god': 'The punishment shall now be administered personally.',
  'story.olympus_offer.sis': 'Will you be paying by the climb?',
  'story.charter_purchase.god': 'The sentence is eternal.',
  'story.charter_purchase.sis': 'So is the contract.',
  'story.first_prestige.god': 'Thanatos returns you to the foot of the hill.',
  'story.first_prestige.sis': 'Same sentence. New understanding.',

  'relic.hermes_seal': 'Hermes Seal',
  'relic.hermes_seal.joke': 'Delivered before the complaint.',
  'relic.daedalus_pin': 'Daedalus Pin',
  'relic.daedalus_pin.joke': 'The spare part was intentional.',
  'relic.danaid_handle': 'Danaid Handle',
  'relic.danaid_handle.joke': 'Handle with care. Contents optional.',
  'relic.ichor_ampoule': 'Sealed Ichor Ampoule',
  'relic.ichor_ampoule.joke': 'Do not remove the stopper.',
  'relic.atlas_shard': 'Atlas Sky Shard',
  'relic.atlas_shard.joke': 'Not a piece of the Earth.',
  'relic.zeus_seal': 'Zeus Seal',
  'relic.zeus_seal.joke': 'Approved under protest.',

  'upgrade.remembered_hand': 'Remembered Hand',
  'upgrade.remembered_hand.desc': 'Begin future runs with the foreman active.',
  'upgrade.known_machinery': 'Known Machinery',
  'upgrade.known_machinery.desc': 'Owned and newly opened sites start with a charged flywheel.',
  'upgrade.standing_orders': 'Standing Orders',
  'upgrade.standing_orders.desc': 'Sites opened after the first start at level 5.',
  'upgrade.familiar_ground': 'Familiar Ground',
  'upgrade.familiar_ground.desc': 'Sites below your highest owned site earn twice as much.',
  'upgrade.signed_in_advance': 'Signed in Advance',
  'upgrade.signed_in_advance.desc': 'Works bought in earlier runs return free when their level is met.',
  'upgrade.eternal_shift': 'Eternal Shift',
  'upgrade.eternal_shift.desc': 'Offline earnings limit rises from 24 to 72 hours.',
  'upgrade.deep_reservoir': 'Deep Reservoir',
  'upgrade.deep_reservoir.desc': 'Charged flywheels speed ascents by 50% instead of 25%.',
  'upgrade.unbroken_memory': 'Unbroken Memory',
  'upgrade.unbroken_memory.desc': 'Double all ordinary income permanently.',

  'target.debris': 'Debris',
  'target.coin_amphora': 'Coin amphora',
  'target.gilded_offering': 'Gilded offering',

  'hint.push': 'Hold the boulder, Space, or the Push button to climb.',
  'hint.improve': 'Spend Obols to Improve Operation. Bigger payouts every climb.',
  'hint.flywheel': 'The falling stone is wasted. A flywheel could catch it.',
  'hint.charge': 'The next descent will charge the flywheel.',
  'hint.foreman': 'Hire the foreman and the hill works without you.',
  'hint.expand': 'Keep earning. The gods are watching your Defiance.',
};

export const ambient: Record<string, string[]> = {
  first_hill: [
    'I have identified a recurring task.',
    'The stone has excellent attendance.',
    'Downhill seems to require fewer qualifications.',
    'Eternal is an ambitious deadline.',
    'The gods have declined my request for a chair.',
    'Same hill. Better margins.',
  ],
  tartarus_rim: [
    'Daedalus says the spare gear is decorative. I remain concerned.',
    'Ixion has never missed a revolution.',
    'The pulley has taken a great weight off my shoulders.',
    'Olympus requests that we stop calling this an opportunity.',
    'The decree says forever. It says nothing about overtime.',
    'We are now suffering at twice the rate.',
  ],
  leaking_heights: [
    'Please do not repair the leak.',
    'The vessel remains empty. The accounts do not.',
    'We have classified the missing bottom as an outlet.',
    'The inspector asked when it would be full.',
    'Apparently, there is no approved form for useful futility.',
    'Another milestone. Still not a drop retained.',
  ],
  bronze_pass: [
    'Talos has requested a larger doorway.',
    'Do not touch the ankle fitting.',
    'The new stone is an excellent conductor of complaints.',
    'Zeus specified mortal labor. We read that carefully.',
    'The gods have increased the burden. Talos seems pleased.',
    'Heavy industry has become quite literal.',
  ],
  skyward_escarpment: [
    'Atlas assures me this is the sky, not the Earth.',
    'The scaffolding now has a weather forecast.',
    'Our overhead has become difficult to estimate.',
    'Olympus objects to the view from below.',
    'The next decree will need a longer scroll.',
    'We have raised expectations and several tons of stone.',
  ],
  olympian_approach: [
    'The stone now carries its own terms and conditions.',
    'Divine marble produces a remarkably ordinary noise.',
    'We have installed a complaint chute. It leads downhill.',
    'Zeus would like to speak to the manager.',
    'I am available for all of eternity. Please make an appointment.',
    'The number no longer fits on the original tablet.',
  ],
};

export function t(key: string): string {
  return en[key] ?? key;
}
